# Utilities Stack - Trivy Server, Dozzle, SOPS
# Deploy via Portainer oder: docker compose up -d

services:
  # ============================================
  # Trivy Server (CLI Scans)
  # ============================================
  trivy-server:
    image: aquasec/trivy:latest
    container_name: trivy-server
    restart: unless-stopped
    # Port 8080 wird NICHT mehr exponiert → nur über Traefik!
    volumes:
      - trivy_cache:/root/.cache
    command: ["server", "--listen", "0.0.0.0:8080"]
    extra_hosts:
      # Container-interne DNS-Auflösung aller DevOps Services über Host → Traefik
      - "traefik.devops.local:host-gateway"
      - "git.devops.local:host-gateway"
      - "ci.devops.local:host-gateway"
      - "dashboard.devops.local:host-gateway"
      - "registry.devops.local:host-gateway"
      - "logs.devops.local:host-gateway"
      - "trivy.devops.local:host-gateway"
    environment:
      - TRIVY_GITHUB_TOKEN=${TRIVY_GITHUB_TOKEN}
      - TRIVY_LISTEN=0.0.0.0:8080
    networks:
      - devops-network
    labels:
      # ==================
      # Traefik Integration
      # ==================
      - "traefik.enable=true"

      # HTTP Router für Trivy API
      - "traefik.http.routers.trivy.rule=Host(`trivy.devops.local`)"
      - "traefik.http.routers.trivy.entrypoints=web"
      - "traefik.http.services.trivy.loadbalancer.server.port=8080"

      # Docker Network für Traefik
      - "traefik.docker.network=devops-network"

  # ============================================
  # Dozzle - Log Viewer
  # ============================================
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    # Port 8080 wird NICHT mehr exponiert → nur über Traefik!
    volumes:
      # Docker Socket für Colima/macOS
      - /Volumes/DockerData/colima/default/docker.sock:/var/run/docker.sock:ro
    extra_hosts:
      # Container-interne DNS-Auflösung aller DevOps Services über Host → Traefik
      - "traefik.devops.local:host-gateway"
      - "git.devops.local:host-gateway"
      - "ci.devops.local:host-gateway"
      - "dashboard.devops.local:host-gateway"
      - "registry.devops.local:host-gateway"
      - "logs.devops.local:host-gateway"
      - "trivy.devops.local:host-gateway"
    environment:
      - DOZZLE_LEVEL=info
      - DOZZLE_TAILSIZE=300
      - DOZZLE_FILTER=name=gitea,name=woodpecker,name=harbor,name=defectdojo,name=trivy
    networks:
      - devops-network
    labels:
      # ==================
      # Traefik Integration
      # ==================
      - "traefik.enable=true"

      # HTTP Router für Dozzle UI
      - "traefik.http.routers.dozzle.rule=Host(`logs.devops.local`)"
      - "traefik.http.routers.dozzle.entrypoints=web"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"

      # Docker Network für Traefik
      - "traefik.docker.network=devops-network"

volumes:
  trivy_cache:
    

networks:
  devops-network:
    external: true
